#!/bin/sh
# -----------------------------------------------------------------------------
# Copyright 2006-2007 Chris Dagdigian (dag@sonsorol.org)
#
#     This file is part of xml-qstat.
#
#     xml-qstat is free software: you can redistribute it and/or modify it under
#     the terms of the GNU Affero General Public License as published by the
#     Free Software Foundation, either version 3 of the License,
#     or (at your option) any later version.
#
#     xml-qstat is distributed in the hope that it will be useful, but
#     WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
#     or FITNESS FOR A PARTICULAR PURPOSE.
#     See the GNU Affero General Public License for more details.
#
#     You should have received a copy of the GNU Affero General Public License
#     along with xml-qstat. If not, see <http://www.gnu.org/licenses/>.
# ------------------------------------------------------------------------------
# Script
#     cocoon
#
# Description
#     Simple start/stop script for the Cocoon server engine
# -----------------------------------------------------------------------------

# 0. Define safe path
PATH=/bin:/usr/bin
#
## CUSTOMIZE AS REQUIRED
#

# 1. Location of cocoon server and java
COCOON_HOME=/data/app/cocoon
JAVA_HOME=/usr/lib/jvm/java

# 2. Downgrade to a non-root user account (adjust if required)
runAs=nobody

export COCOON_HOME JAVA_HOME PATH
unset  DISPLAY    # extra safety

#---------------------------------------------------------------------------
# The following lines provide the necessary info for adding a startup script
# according to the Linux Standard Base Specification (LSB).
#
### BEGIN INIT INFO
# Provides:       xmlqstat.cocoon
# Required-Start: $network $remote_fs
# Should-Start:   network-remotefs
# Required-Stop:
# Default-Start:  3 5
# Default-Stop: 0 1 2 6
# Description:  start cocoon for xmlqstat
### END INIT INFO
#---------------------------------------------------------------------------

# this script should never run as root
if [ "$UID" -eq 0 -a "${runAs:=nobody}" != root ]
then
    exec sudo -S -u $runAs $0 $@
    exitcode=$?       # retain exitcode

    [ "$exitcode" == 0 ] || {
        echo "could not change to $runAs"
        exit $exitcode
    }
fi

daemon=$COCOON_HOME/cocoon.sh
name=cocoon
desc="Apache Cocoon"

# logging
LOG=/var/log/cocoon
LOG=/dev/null

#
# check that the daemon program is installed
#
[ -f $daemon -a -x $daemon ] || {
    echo "$daemon not found"
    exit 5      # LSB compliant exit status - program is not installed
}

set -e
case "$1" in
start)
    echo -n "Starting $desc: "
    $daemon servlet >> $LOG 2>&1 &
    echo "$name"
    ;;

stop)
    echo -n "Stopping $desc: "
    # get pid
    pid=$(ps aux | awk '{if (/java/ && /cocoon/ && !/awk/) print $2}')
    if [ -z "$pid" ]
    then
        echo "process not found"
    else
        echo "sending TERM signal"
        kill -15 $pid
    fi
    ;;

restart)
    ## Stop (if running) and start anew
    $0 stop
    $0 start $@
    ;;

*)
    echo "Usage: $0 {start|stop|restart}" >&2
    exit 1
    ;;
esac

exit 0
# -------------------------------------------------------------- end-of-file
