#!/bin/sh
# -----------------------------------------------------------------------------
# Copyright (c) 2009-2012 Mark Olesen
#
# License
#     This file is part of xml-qstat.
#
#     xml-qstat is free software: you can redistribute it and/or modify it under
#     the terms of the GNU Affero General Public License as published by the
#     Free Software Foundation, either version 3 of the License,
#     or (at your option) any later version.
#
#     xml-qstat is distributed in the hope that it will be useful, but
#     WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
#     or FITNESS FOR A PARTICULAR PURPOSE.
#     See the GNU Affero General Public License for more details.
#
#     You should have received a copy of the GNU Affero General Public License
#     along with xml-qstat. If not, see <http://www.gnu.org/licenses/>.
#
# Script
#     httpi
#
# Description
#     Simple start/stop script for the httpi web-server
# -----------------------------------------------------------------------------

# 0. Define safe path for older versions of HTTPi
PATH=/usr/bin:/bin
#
## CUSTOMIZE AS REQUIRED
#
# 1. Location of httpi server program
HTTPI=/data/caeapp/local/www/httpi/httpi

# 2. Downgrade to a non-root user account (adjust if required)
runAs=nobody

export PATH
unset DISPLAY SGE_ARCH SGE_CELL SGE_ROOT # extra safety

#------------------------------------------------------------------------------
# The following lines provide the necessary info for adding a startup script
# according to the Linux Standard Base Specification (LSB).
#
### BEGIN INIT INFO
# Provides:       httpi-xmlqstat
# Required-Start: $network $remote_fs
# Should-Start:   network-remotefs
# Required-Stop:
# Default-Start:  3 5
# Default-Stop: 0 1 2 6
# Description:  start httpi for xmlqstat
### END INIT INFO
#------------------------------------------------------------------------------

# this script should never run as root
if [ "$UID" -eq 0 -a "${runAs:=nobody}" != root ]
then
    exec sudo -S -u $runAs $0 $@
    exitcode=$?       # retain exitcode

    [ "$exitcode" == 0 ] || {
        echo "could not change to $runAs"
        exit $exitcode
    }
fi

daemon=$HTTPI
desc="httpi webserver"

# logging
LOG=/var/log/httpi
LOG=/dev/null

#
# check that the daemon program is installed
#
check_installed()
{
    [ -f $daemon -a -x $daemon ] || {
        echo "$daemon not found"
        exit 5      # LSB exit status - program is not installed
    }
}


# with second argument, take as the name of the httpi server
if [ "$#" -ge 2 ]
then
    daemon=$2
    check_installed
fi


set -e
case "$1" in
start)
    check_installed

    echo -n "Starting $desc: "
    $daemon >> $LOG 2>&1 &
    echo "httpi ($daemon)"
    ;;

stop)
    # get pid
    pid=$(/bin/ps ax -o pid,command | /bin/awk '{if ($2 ~ /^dhttpi:/) {print $1}}')

    echo -n "Stopping $desc: "
    if [ -z "$pid" ]
    then
        echo "process not found"
    else
        echo "sending TERM signal ($pid)"
        kill -15 $pid
    fi
    ;;

restart)
    ## Stop (if running) and start anew
    shift
    check_installed
    $0 stop
    $0 start $@
    ;;

*)
    echo "Usage: $0 {start|stop|restart} [httpi-location]" >&2
    exit 1
    ;;
esac

exit 0
# ----------------------------------------------------------------- end-of-file
