#!/bin/sh
# -----------------------------------------------------------------------------
# Copyright (c) 2006-2007 Chris Dagdigian (dag@sonsorol.org)
#
# License
#     This file is part of xml-qstat.
#
#     xml-qstat is free software: you can redistribute it and/or modify it under
#     the terms of the GNU Affero General Public License as published by the
#     Free Software Foundation, either version 3 of the License,
#     or (at your option) any later version.
#
#     xml-qstat is distributed in the hope that it will be useful, but
#     WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
#     or FITNESS FOR A PARTICULAR PURPOSE.
#     See the GNU Affero General Public License for more details.
#
#     You should have received a copy of the GNU Affero General Public License
#     along with xml-qstat. If not, see <http://www.gnu.org/licenses/>.
#
# Script
#     xmlqstat-cacher
#
# Description
#     Simple start/stop script for the perl daemon that caches
#     GridEngine XML status data for the "xml-qstat" web application
# -----------------------------------------------------------------------------

# 0. Define safe path
PATH=/usr/bin:/bin
#
## CUSTOMIZE AS NEEDED
#
# 1. Downgrade to a non-root user account (adjust as required)
runAs=cfdadmin

# 2. Location of the script
CACHER_HOME=/opt/xml-qstat/scripts

# 3. Require GridEngine for later queries
SGE_ROOT=/opt/grid
SGE_CELL=default

#---------------------------------------------------------------------------
# The following lines provide the necessary info for adding a startup script
# according to the Linux Standard Base Specification (LSB).
#
### BEGIN INIT INFO
# Provides:       xmlqstat.cacher
# Required-Start: $network $remote_fs
# Should-Start:   network-remotefs
# Required-Stop:
# Default-Start:  3 5
# Default-Stop: 0 1 2 6
# Description:  start xmlqstat cacher
### END INIT INFO
#---------------------------------------------------------------------------

# this script should run as 'runAs'
if [ "$UID" -eq 0 -a "${runAs:=root}" != root ]
then
    exec sudo -S -u $runAs $0 $@
    exitcode=$?       # retain exitcode

    [ "$exitcode" == 0 ] || {
        echo "could not change to $runAs"
        exit $exitcode
    }
fi

# Init GridEngine path/environment variables
if [ -f $SGE_ROOT/$SGE_CELL/common/settings.sh ]
then
    export SGE_ROOT SGE_CELL
    . $SGE_ROOT/$SGE_CELL/common/settings.sh
else
    unset SGE_ROOT SGE_CELL
fi


daemon=$CACHER_HOME/xmlqstat-cacher.pl
name=xmlqstat-cacher
desc="GridEngine XML Status Caching Daemon"

[ -f $daemon -a -x $daemon ] || {
    echo "$daemon not found"
    exit 5      # LSB compliant exit status - program is not installed
}

case "$1" in
start)
    echo -n "Starting $desc: "
    $daemon -d
    echo "$name"
    ;;

stop)
    echo -n "Stopping $desc: "
    $daemon -k
    echo "$name"
    ;;

restart)
    ## Stop (if running) and start anew
    $0 stop
    $0 start
    ;;

*)
    echo "Usage: $0 {start|stop|restart}" >&2
    exit 1
    ;;
esac

exit 0
# -------------------------------------------------------------- end-of-file
